name: CI Workflow

on:
  push:
    branches:
      - '**'  # Run on pushes to all branches
  pull_request:
    branches:
      - '**'  # Run on pull requests to all branches


jobs:
  build:
    runs-on: ubuntu-latest
    env:  # Define static global environment variables
      DIST_REPO: "f5-openstack-agent-dist"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Dynamic Environment Variables
        id: set_env_vars
        run: |
          # Get package version
          PKG_VERSION=$(python -c "import f5_openstack_agent; print(f5_openstack_agent.__version__)")

          # Get package release version
          PKG_RELEASE=$(python ${DIST_REPO}/scripts/get-version-release.py --release)

          # Set other variables based on the above
          echo "PKG_VERSION=${PKG_VERSION}" >> $GITHUB_ENV
          echo "PKG_RELEASE=${PKG_RELEASE}" >> $GITHUB_ENV
          echo "PKG_RELEASE_EL7=${DIST_REPO}/rpms/build/f5-openstack-agent-${PKG_VERSION}-${PKG_RELEASE}.el7.noarch.rpm" >> $GITHUB_ENV
          echo "PKG_RELEASE_1404=${DIST_REPO}/deb_dist/python-f5-openstack-agent_${PKG_VERSION}-${PKG_RELEASE}_1404_all.deb" >> $GITHUB_ENV
          echo "RELEASE_TAG=v$(echo $PKG_VERSION | cut -d . -f 1,2)" >> $GITHUB_ENV

      - name: Use Environment Variables
        run: |
          echo "Package Version: $PKG_VERSION"
          echo "Package Release: $PKG_RELEASE"
          echo "EL7 Package Path: $PKG_RELEASE_EL7"
          echo "1404 Package Path: $PKG_RELEASE_1404"
          echo "Release Tag: $RELEASE_TAG"

      - name: Set up Python 2
        run: |
          sudo rm -f $(which python) $(which pip)
          # sudo apt-get install python2.7
          sudo apt install python2.7 python-pip
          sudo apt update
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2.7 get-pip.py
          # sudo ln -sf "$(which python2.7)" "$(dirname $(which python2.7))/python"

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '2.7'  # Specify Python version

      - name: Download Docker images
        run: |
          wget https://github.com/F5Networks/docker-images/raw/master/centos:6.tar.gz
          wget https://github.com/F5Networks/docker-images/raw/master/centos:7.tar.gz
          wget https://github.com/F5Networks/docker-images/raw/master/f5devcentral_containthedocs:latest.tar.gz
          wget https://github.com/F5Networks/docker-images/raw/master/ubuntu:trusty.tar.gz

      - name: Load Docker images
        run: |
          docker load -i centos:6.tar.gz
          docker load -i centos:7.tar.gz
          docker load -i f5devcentral_containthedocs:latest.tar.gz
          docker load -i ubuntu:trusty.tar.gz

      - name: Install pip and dependencies
        run: |
          echo "Package Version: $PKG_VERSION"
          echo "Package Release: $PKG_RELEASE"
          echo "EL7 Package Path: $PKG_RELEASE_EL7"
          echo "1404 Package Path: $PKG_RELEASE_1404"
          echo "Release Tag: $RELEASE_TAG"
          sudo python -m pip install pip==19.0.3
          # pip install -Iv tox==3.25.1
          sudo pip2 install tox==3.25.1
          sudo pip2 install -r requirements.style.txt
